export const keys = {
  config: ['config'] as const,
  me: ['me'] as const,
  restaurants: (q: object) => ['restaurants', q] as const,
  restaurant: (slug: string) => ['restaurant', slug] as const,
  foods: (q: object) => ['foods', q] as const,
  food: (id: string) => ['food', id] as const,
  suggest: (q: string) => ['suggest', q] as const,
  search: (q: string) => ['search', q] as const,
  trending: ['trending'] as const,
  coupons: ['coupons'] as const,
  cart: ['cart'] as const,
  orders: (q: object) => ['orders', q] as const,
  order: (id: string) => ['order', id] as const,
  notifications: ['notifications'] as const,
  unread: ['notifications', 'unread'] as const,
  favorites: ['favorites'] as const,
  favoriteIds: ['favorites', 'ids'] as const,
  rewards: ['rewards'] as const,
  forYou: (authed: boolean) => ['recommendations', 'for-you', authed] as const,
  smartReorder: ['recommendations', 'smart-reorder'] as const,
  alsoOrdered: (id: string) => ['recommendations', 'also', id] as const,
  reviews: (q: object) => ['reviews', q] as const,
  addresses: ['addresses'] as const,
};
